version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - build_docker_image:
          requires:
            - maven/test


jobs:
  build_docker_image:
    docker:
      - image: openjdk:8-jdk
        auth:
          username: mhalukt
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t ci-image:latest
