orbs:
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          auth:
            username: mhalukt
            password: $DOCKERHUB_PASSWORD
          update-description: true