version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - build_docker_image:
          requires:
            - maven/test


jobs:
  build_docker_image:
    docker:
      - image: ci-image:latest
    steps:
      - checkout
      - run:
          name: Set up tag
          command: echo "export TAG=0.1.$CIRCLE_SHA1" >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build -t ci-image:latest
