orbs:
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: haluktiras/tictactoe
          use-docker-credentials-store: true